apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "storage.simplyblock.io/v1alpha1",
          "kind": "Device",
          "metadata": {
            "labels": {
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "simplyblock-operator"
            },
            "name": "device-sample"
          },
          "spec": {
            "clusterName": "sample-cluster"
          }
        },
        {
          "apiVersion": "storage.simplyblock.io/v1alpha1",
          "kind": "Lvol",
          "metadata": {
            "labels": {
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "simplyblock-operator"
            },
            "name": "lvol-sample"
          },
          "spec": {
            "clusterName": "sample-cluster",
            "poolName": "pool-1"
          }
        },
        {
          "apiVersion": "storage.simplyblock.io/v1alpha1",
          "kind": "Pool",
          "metadata": {
            "labels": {
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "simplyblock-operator"
            },
            "name": "pool-sample"
          },
          "spec": {
            "clusterName": "sample-cluster",
            "name": "pool-1"
          }
        },
        {
          "apiVersion": "storage.simplyblock.io/v1alpha1",
          "kind": "SnapshotReplication",
          "metadata": {
            "labels": {
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "simplyblock-operator"
            },
            "name": "snapshotreplication-sample"
          },
          "spec": {
            "sourceCluster": "source-cluster",
            "targetCluster": "target-cluster",
            "targetPool": "target-pool"
          }
        },
        {
          "apiVersion": "storage.simplyblock.io/v1alpha1",
          "kind": "StorageBackup",
          "metadata": {
            "name": "storagebackup-sample"
          },
          "spec": {
            "clusterName": "my-cluster",
            "pvcRef": {
              "name": "my-pvc"
            }
          }
        },
        {
          "apiVersion": "storage.simplyblock.io/v1alpha1",
          "kind": "StorageCluster",
          "metadata": {
            "labels": {
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "simplyblock-operator"
            },
            "name": "storagecluster-sample"
          },
          "spec": {
            "backup": {
              "credentialsSecretRef": {
                "name": "sample-cluster-backup"
              },
              "localEndpoint": "http://10.10.11.10:9000",
              "localTesting": true,
              "secondaryTarget": 0,
              "snapshotBackups": true,
              "withCompression": false
            },
            "clusterName": "sample-cluster"
          }
        },
        {
          "apiVersion": "storage.simplyblock.io/v1alpha1",
          "kind": "StorageNode",
          "metadata": {
            "labels": {
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "simplyblock-operator"
            },
            "name": "storagenode-sample"
          },
          "spec": {
            "clusterImage": "simplyblock/snode:latest",
            "clusterName": "sample-cluster",
            "maxLogicalVolumeCount": 256,
            "workerNodes": [
              "worker-node-1"
            ]
          }
        },
        {
          "apiVersion": "storage.simplyblock.io/v1alpha1",
          "kind": "Task",
          "metadata": {
            "labels": {
              "app.kubernetes.io/managed-by": "kustomize",
              "app.kubernetes.io/name": "simplyblock-operator"
            },
            "name": "task-sample"
          },
          "spec": {
            "clusterName": "sample-cluster"
          }
        }
      ]
    capabilities: Basic Install
    createdAt: "2026-04-30T16:48:18Z"
    operators.operatorframework.io/builder: operator-sdk-v1.42.2
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v4
  name: simplyblock-operator-rhmp.v0.1.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: Device
      name: devices.storage.simplyblock.io
      version: v1alpha1
    - kind: Lvol
      name: lvols.storage.simplyblock.io
      version: v1alpha1
    - kind: Pool
      name: pools.storage.simplyblock.io
      version: v1alpha1
    - kind: SnapshotReplication
      name: snapshotreplications.storage.simplyblock.io
      version: v1alpha1
    - kind: StorageBackup
      name: storagebackups.storage.simplyblock.io
      version: v1alpha1
    - kind: StorageCluster
      name: storageclusters.storage.simplyblock.io
      version: v1alpha1
    - kind: StorageNode
      name: storagenodes.storage.simplyblock.io
      version: v1alpha1
    - kind: Task
      name: tasks.storage.simplyblock.io
      version: v1alpha1
  description: Simplyblock Operator description. TODO.
  displayName: Simplyblock Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        - apiGroups:
          - ""
          resources:
          - nodes
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - ""
          resources:
          - persistentvolumeclaims
          - persistentvolumes
          verbs:
          - create
          - get
          - list
          - watch
        - apiGroups:
          - ""
          resources:
          - pods
          verbs:
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - secrets
          - services
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - discovery.k8s.io
          resources:
          - endpointslices
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - policy
          resources:
          - poddisruptionbudgets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - storage.k8s.io
          resources:
          - storageclasses
          verbs:
          - create
          - delete
          - get
          - list
          - watch
        - apiGroups:
          - storage.simplyblock.io
          resources:
          - backuprestores
          - devices
          - lvols
          - pools
          - snapshotreplications
          - storagebackups
          - storageclusters
          - storagenodes
          - tasks
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - storage.simplyblock.io
          resources:
          - backuprestores/finalizers
          - devices/finalizers
          - lvols/finalizers
          - pools/finalizers
          - snapshotreplications/finalizers
          - storagebackups/finalizers
          - storageclusters/finalizers
          - storagenodes/finalizers
          - tasks/finalizers
          verbs:
          - update
        - apiGroups:
          - storage.simplyblock.io
          resources:
          - backuprestores/status
          - devices/status
          - lvols/status
          - pools/status
          - snapshotreplications/status
          - storagebackups/status
          - storageclusters/status
          - storagenodes/status
          - tasks/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - apps
          resources:
          - daemonsets
          verbs:
          - create
          - delete
          - patch
          - update
          - watch
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - clusterrolebindings
          - clusterroles
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: simplyblock-operator-controller-manager
      deployments:
      - label:
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/name: simplyblock-operator
          control-plane: controller-manager
        name: simplyblock-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              app.kubernetes.io/name: simplyblock-operator
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              annotations:
                kubectl.kubernetes.io/default-container: manager
              labels:
                app.kubernetes.io/name: simplyblock-operator
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --metrics-bind-address=:8443
                - --leader-elect
                - --health-probe-bind-address=:8081
                command:
                - /manager
                image: quay.io/simplyblock-io/simplyblock-operator:0.1.0
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 500m
                    memory: 128Mi
                  requests:
                    cpu: 10m
                    memory: 64Mi
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop:
                    - ALL
                  readOnlyRootFilesystem: true
              securityContext:
                runAsNonRoot: true
                seccompProfile:
                  type: RuntimeDefault
              serviceAccountName: simplyblock-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: simplyblock-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - simplyblock-operator
  links:
  - name: Simplyblock Operator
    url: https://simplyblock-operator.domain
  maintainers:
  - email: your@email.com
    name: Maintainer Name
  maturity: alpha
  provider:
    name: Provider Name
    url: https://your.domain
  version: 0.1.0
